### PR TITLE
Enable alias resolution in $import paths

### PR DESCRIPTION
**Pull request by AMZN-alexpete**
## What does this PR do?
This change adds a custom importer that uses ResolvePath() to resolve any aliases in the path so that you can $import files from other gems or the engine itself.

## How was this PR tested?
By adding using aliases instead of absolute paths for the [vegetation bending tutorial](https://github.com/o3de/sample-code-gems/tree/main/atom_gems/AtomTutorials): e.g. `@gem_root:Atom_Feature_Common/etc.`

Signed-off-by: alexpete <alexpete@amazon.com>

### CODE REVIEW

**Comment by AMZN-alexpete** [comment]
> I just submitted changes to the JSONImporter to "replace" and not "resolve" the aliases in the path about an hour ago: [o3de@82f31dd](https://github.com/o3de/o3de/commit/82f31dd8488132469def5c706d251ac80816d372)
> 
> "Resolving" makes a relative path absolute, while "ReplaceAlias" will only replace an alias if it exist, but it will not make a relative path absolute.

Awesome, I'll test that change with this use case and likely close this PR

**Comment by AMZN-alexpete** [comment]
This issue was resolved by https://github.com/o3de/o3de/commit/82f31dd8488132469def5c706d251ac80816d372

**Comment by AMZN-alexpete** [comment]
I spoke too soon.  This does not handle the case where the importedFilePath has an alias in the middle - i.e.
```
importedFilePath = d:\path\to\o3de\@gemroot:Atom_Feature_Common@\some\path
```
which is always the case because `ResolveImports` calls `ResolveImport` with importedFilePath as an absolute path. In this case the relative path exists in importDirective as `@gemroot:Atom_Feature_Common@\some\path`

**Comment by lumberyard-employee-dm** [comment]
The alias would need to be should be resolved before being appening to the engine path and then the AZ::IO::Path::operator/ should be used to smartly append the paths.

**Pull request closed without merging**
