### PR TITLE
Updated pillow requirements.

### PR DESCRIPTION
**Pull request by AMZN-scspaldi**
Signed-off-by: scspaldi <scspaldi@amazon.com>

### CODE REVIEW

**Review by evanchia-ly-sdets — APPROVED** [review]

**Comment by tonybalandiuk** [comment]
**Exception Tracking**

- [ ] 1.    Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.    Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
- [ ] 3.	Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 6.	If all approvals are accepted exception PR is merged
- [ ] 7.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 8.	Exception is complete

**Comment by AMZN-Dk** [comment]
Approved from owning and testing SIG.

**Comment by Ulrick28** [comment]
I am not sure sig-UX makes sense as an approver for this PR, it is a backend dependency update and does not affect UX/UI in any way.

**Review by Ulrick28 — APPROVED** [review]

**Comment by Ulrick28** [comment]
Still concerned this is for development and not for stabilization. And why does a development merge require 6 approvals?

**Comment by amzn-changml** [comment]
This PR is targeting `aws-lumberyard-dev:development` which is our fork. You need to retarget the destination to `o3de:development` to have the correct number of approvals and checks

**Comment by Ulrick28** [comment]
Ok, So while the code will fix the issue, this PR is merging to the fork. Hence all the weird requirements. This PR needs to be cancelled and recreated to target stabilization.

**Comment by evanchia-ly-sdets** [comment]
Will reopen a new PR for this

**Pull request closed without merging**
